In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [4]:
df = pd.read_excel('task_1_2.xlsx')

In [5]:
df.head()

         Date      series1
0  2015-01-01  1006.699649
1  2015-01-02  3197.751826
2  2015-01-03  3217.491035
3  2015-01-04  2151.573759
4  2015-01-05  4243.929892

In [6]:
df.isna().sum()

Date       0
series1    0
dtype: int64

In [12]:
df.sort_values('Date')

           Date      series1
0    2015-01-01  1006.699649
1    2015-01-02  3197.751826
2    2015-01-03  3217.491035
3    2015-01-04  2151.573759
4    2015-01-05  4243.929892
...         ...          ...
1637 2019-06-26  4007.059387
1638 2019-06-27  4836.106157
1639 2019-06-28  4895.323783
1640 2019-06-29  4086.016222
1641 2019-06-30  3572.796793

[1642 rows x 2 columns]

In [13]:
df.set_index("Date", inplace=True)

In [15]:
df = df.asfreq("D")

In [16]:
df.head()

                series1
Date
2015-01-01  1006.699649
2015-01-02  3197.751826
2015-01-03  3217.491035
2015-01-04  2151.573759
2015-01-05  4243.929892

In [19]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
from statsmodels.tsa.holtwinters import ExponentialSmoothing

In [20]:
train = df["series1"].iloc[:-90]
test = df["series1"].iloc[-90:]

In [21]:
model = ExponentialSmoothing(
    train, trend="add", seasonal="add", seasonal_periods=365
).fit()

In [22]:
test_predictions = model.forecast(len(test))

# Оценка качества (MAE, RMSE, MAPE)
mae = mean_absolute_error(test, test_predictions)
rmse = np.sqrt(mean_squared_error(test, test_predictions))
mape = np.mean(np.abs((test - test_predictions) / test)) * 100

print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"MAPE: {mape:.2f}%")

MAE: 662.60
RMSE: 850.56
MAPE: 17.41%